### ISSUE TITLE
Reintegrate Slack with Hackerspace

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#239]
# Background

New Slack App created in #232.

This functionality to retrieve user scopes and use the Slack API to open chat broke at the end of 2020 when our planned changed.

It would be great to re implement it and add some new functionality.

# Tasks

- [x] Re implement Slack functionality into Hackerspace.

# Resources

This task requires a little bit of fiddling around with Hackerspace and Slack API

- [ ] Set up your own Hackerspace development environment.
- [ ] Set up your own Slack app on you own account and set the SLACK_ environment variable in`config/application.yml` (see README)
- [ ] Create a new branch and revert the commit that removed the slack button from view (`$ git revert a3453653e46ba)
- [ ] Get the integration working.

# Notes

From Luke: I almost had this up and running again except the the [conversations.open](https://api.slack.com/methods/conversations.open) api method which we implement at `hackerspace3/app/controllers/profiles_controller.rb:30` no longer returns the channel id of the desired users but the channel id of the app bot 🤷🏻‍♂️

Solution is probably in configuring something in but also possible Hackerspace is configured incorrectly.

**Comment by cassar** [comment]
Completed with special thanks to @00Chaotic 🙏
