### ISSUE TITLE
Refactor Challenge Judging Controller

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#24]
## Background

Current implementation messy, error prone, and not easily transferable to other sections of the site.

Move bulk of controller logic into its own model.

New implementation must be more 'restful' with nothing saved till the POST create method is accessed.

## Tasks

- [x] Rename Judgment to Score
- This make more sense given Scorecard and Scoreboard and is less error prone, eg judgment becomes judgements (at least in the code)
- [x] Rename Scorecard model to Header
- This will make the model more indicative of what it actually is; a Header and its Scores constitute part or all of a Scorecard.
- [x] Rename Judgeable to Scoreable.
- While we're at it.
- [ ] Create a virtual model Scorecard which will combine the Header with its Scores.
- This new virtual model should be able to handle all the CRUD methods typical of a persistent model.
- [ ] Create a virtual model Scoreboard which will collect scorecards given a Team, Competition, Challenge, or Entry
