### ISSUE TITLE
Automation of Sign Up Users to Mailchimp Mailing List

### ISSUE THREAD

**Issue by ooliviarr** [govhackaustralia/hackerspace3#252]
# Background

Currently we don't have an automated way to add users to our Mail Chimp mailing list.

# Task

- [x] Investigate Mail Chimp docs and see what API calls need to be made.
- [x] Automatically add User to a list when they hit the subscribe button.
- [x] Automatically unsubscribe them from a list when they hit unsubscribe.

**Comment by cassar** [comment]
# Background

Currently we don't have an automated way to add users to our Mail Chimp mailing list.

# Task

-[ ] Investigate Mail Chimp docs and see what API calls need to be made.
-[ ] Automatically add User to a list when they hit the subscribe button.
-[ ] Automatically unsubscribe them from a list when they hit unsubscribe.

**Comment by karwalski** [comment]
Looks like there is a gem available
https://github.com/mailchimp/mailchimp-marketing-ruby

What we want to use is the add a member to a list call
https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/

I can generate keys when ready

**Comment by cassar** [comment]
Fantastic @karwalski 👏

Will try and hook that up soon.

We probably want a remove-member-from-list call as well no?

**Comment by cassar** [comment]
There is also an issue of people hitting unsubscribe from a mailchimp email and this not updating in the Hackerspace 😬
