### ISSUE TITLE
Way to track which datasets and resources where clicked on.

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#277]
# Background

We require a way to gauge which resources (datasets and sponsor tools) are used by participants.

# [Google Analytics Route]

- [x] ~Figure out how to do this with Google Analytics.~
  - Decided not to go with this due to time constraints.

# Tasks [Hackerspace Route]

- [x] Move Sponsor resources into model (separate ticket).
  - Completed in #302 
- [x] New Model Access/Utilisation with attributes
  - user_id
  - resource_type
  - resource_id
- [x] New controller to log interaction in model
- [ ] New UI to display interactions.
