### ISSUE TITLE
Create "Open Public Group Chat" in Slack.

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#287]
## Background

With another year of remote events likely, we need better ways to keep in touch with the teams.

## Proposal

A "Open Public Chat" Button that will direct a user to a public chat for a particular team project.

## Features

- Slack public channel is automatically created
  - Created Slack channel when the team is created
  - Channel name will be Team identifier.
- Authenticated users can access the team channel from project page.
  
## Tasks

- [x] Research what interactions need to be made with the Slack API. @00Chaotic 
- [ ] Implement necessary interaction in Hackerspace. @cassar 

## Future

- [ ] Find a place in the sign up flow to encourage a user to connect their Slack account.
