### ISSUE TITLE
Show Less Shell Teams

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#297]
## Background

The start of the competition can be quite chaotic with many teams being created but not getting used.

## Ideas

- [ ] Remove the teams without any members.
- [ ] Don't show teams who haven't entered challenges.
- [ ] Show a message in the team UI that says their project will appear when they enter a challenge.

## Tasks

- [ ] Figure out a way to reduce the number of shell teams that are showed on the Hackerspace public teams page.
  - Having a publish button for the teams?
  - Only showing teams that have entered a challenge or two?
- [ ] Implement solution.
