### ISSUE TITLE
Move Project Name URL Identifier to Team Model

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#31]
Currently each Project version has it's own identifier.

When a second project version is added, the id is suffixed to the project name.

Projects are then retrieved by...
- Searching for a project name
- Connecting that with the team.
- And then retrieving the team's current project.

This work perfectly fine at the moment but future competitions want this id suffixed dropped (if there is not other project names with that name) and the project name to be kept with the Team object.

# Tasks

- [ ] Create an identifier attribute in the team object.
- [ ] Create a data migration so that all the team's current_project identifier get transferred over.
- [ ] Remove the identifier on the Project model.

This can all be done in the same migration, should be made reversible though.

- [ ] Move Project update identifier logic to Team.
- [ ] Make sure that controllers are querying the Team model for the identifier now.

**Comment by cassar** [comment]
Leaving as is so that old project URLs will still work when the project changes it's name.
