### ISSUE TITLE
Duplicate Project Check

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#36]
## Background

Currently there are no checks to see if a project has been used more than once.

The management team should have a way to see if a project has been used multiple times.

## Tasks

- [ ] Look into libraries that can be used to check the similarity of different data structures.
- [ ] Determine when the functionality should be utilised.
  - When an entry is made to a challenge?
  - When a project is suspected of being duplicated?
- [ ] Determine how this functionality is to be utilised.
  - As a separate worker process?
