### ISSUE TITLE
Single Competition Event Registrations

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#39]
## Background

Currently Competitors are able to register for as many Competition Events as they like.

From Competition 2019, Competitors will only be able to register for one competition event.

They will be able to cancel their registration and join another, but only if their team isn't 'relying on them being registered in that Region.

## Tasks

- [x] Add validation on the Registration model to prevent registering for multiple Competition events.
- [x] Make it more obvious on the Account Management page what type of Event a User has signed up to.
- [x] Prevent users from navigating to the new registration form if they are already registered for a Competition Event.
  -  Something like, 'You are already registered for a Competition Event'
- [x] Signify to the User at appropriate points in the application that their limit of Competition Event Registrations has been reached.
