### ISSUE TITLE
Add AWS Credits Required Field to User Model

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#56]
## Background

The Competition requires information be collected re whether a participant requires aws credits.

## Tasks

- [x] Add the required field to the user model.
- [x] Integrate into Competition Registration form.
- [x] Integrate information into admin event view.
