### ISSUE TITLE
Redirect New Users to Event Registration Page after Sign in/up

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#59]
## Background

Currently new users are deposited on the account management page or on the home screen.

## Tasks

- [ ] ~Set a session variable to store the event id when a user clicks on the 'Sign in to Register button.~ 
  - Already set with devise
- [x] Break the "New User" functionality into a separate controller. 
- [x] Have the user redirected to the event registration screen on successful sign up.

**Comment by cassar** [comment]
Complete.
