### ISSUE TITLE
Add Slack Handle Attribute to User Model

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#62]
## Background

This is required to get in touch with participants on slack.

## Tasks

- [x] Add slack_handle attribute to User model.
- [x] Add to 
  - [x] Events Registrations Page (and CSV)
  - [x] Admin Team management page.
