### ISSUE TITLE
Better Team Entry Explanations

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#66]
## Background 

Currently there is not enough explanation given when a team is or isn't able to join a challenge during the competition weekend.

## Tasks

- [ ] Notify when a team is not eligible to enter a challenge.
- [ ] Notify when team has reached their limits for the remaining checkpoints.
- [ ] Notify when checkpoints have passed.
