### ISSUE TITLE
Implement Holder Model

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#78]
## Background

Competition specific information is required to be stored for participants.

There is currently no way to do this.

## Tasks

- [ ] Implement an (Assignment) Holder model to replace Event Assignment.
 - Belongs to Competition and User.
 - Has many Assignments and Registrations.
 - Any attribute required to be collect from competition to competition (currently only: aws_credits_requested)
- [ ] Redirect all the code that used to use Event Assignment to Holder.
  - Remove all allowance to VIP as it is not used.
- [ ] Redirect competition retrieval from assignment to new holder model.
  - Remove callback to set Competition on new Assignments.
- [ ] Migrate all Event Assignment Production data to Holder.
  - Create Holders for every Assignment.
  - Migrate all values or aws_credits_requested to Holders for competition 2019.
  - Remove the aws_credits_requested column from User.
  - Delete all the event assignments.
  - Remove the competition_id from Assignment.
