### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#79]
## Background

The logo has changed for the 2020 competition.

Assigned to @waiholiu

## Tasks

- [x] Provide new bannerlogo.png
- [x] Provide new logo for favicon.
  - Just a square logo, I can generate the favicon (Cassar)
- [ ] Replace all instances of the logo.

## Notes

- Existing images can be found in `app/assets/images`
- Use the [favicon genenerator ](https://realfavicongenerator.net/favicon/ruby_on_rails#.Xv0Of_IRV24)
- The mailer layout will also need to be updated.

**Comment by thesummerbard** [comment]
[GOVHACK LOGO Finals- to be used.zip](https://github.com/govhackaustralia/hackerspace3/files/4857286/GOVHACK.LOGO.Finals-.to.be.used.zip)

@cassar

**Comment by cassar** [comment]
There is a [wizard](https://realfavicongenerator.net/favicon/ruby_on_rails#.Xv0Of_IRV24) I  use for the favicons, so that's not a problem.

**Comment by waiholiu** [comment]
Hi @cassar 

Alright I've re-generated the favicons using the new logos. They can be seen on this branch.(https://github.com/waiholiu/hackerspace3/tree/updatelogo)

The banner logo contains the words hackerspace at the bottom. That's not included in any of the images. Do we have that image file anywhere or do you want me to try to make it myself? 

The footer as you mentioned in the slack channel, is an SVG file. Any reason this has to stay an SVG file? Can we just stick one of the new PNG files in there instead? The only thing that will be missing will be the long horizontal line going across.

**Comment by mattcen** [comment]
@waiholiu We won't have that image currently. I'd probably suggest taking the existing `bannerlogo.png`, editing it to cut out the logo above the horizontal line, and drop the contents of `Asset 4@8x.png` in its place.

**Comment by mattcen** [comment]
Looks like @Cruion updated the current banner logo in https://github.com/waiholiu/hackerspace3/commit/26b3fd01. Maybe he has the source file he created it with? If not, shouldn't be too hard to rebuild.

**Comment by Cruion** [comment]
I will check the logo out in a little bit and should be able to get you a production ready logo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by waiholiu** [comment]
I've updated with new logos and refreshed favicon.

The footer looks slightly different though as can be seen below. The new images don't have that gradient line going down the middle. 

![image](https://user-images.githubusercontent.com/8047097/86920134-9d6cbf80-c16c-11ea-9a4f-74ba62eb72d2.png)

![image](https://user-images.githubusercontent.com/8047097/86920161-af4e6280-c16c-11ea-9442-5d2a05ea3e8c.png)

**Comment by cassar** [comment]
I think that's fine 👍
