### ISSUE TITLE
Fix DataTable to Persist Search Params and Expand Usage

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#82]
## Background

The current implementation does not persist the search options when navigating back.

The data table is pretty good, and should be used wherever there are lots of results returned.

## Tasks

- [x] Fix this.
- [x] Create common datatable setting in Application JS
- [x] Add data table to..
  - [x] events/event_id/team
  - [x] admin/users
  - [x] admin/users/user_id/show
  - [x] admin/competitions/competition_id/events
  - [x] admin/competitions/3/sponsors
  - [x] admin/events/event_id/registrations
  - [x] admin/competitions/.../regions
  - [x] admin/competitions/.../scorecards
  - [x] admin/competitions/.../sponsorship_types
  - [x] admin/competitions/.../teams
  - [x] challenges/challenge_id/teams (new view)

- [x] Fix error with functionality not working with navigate back.
