### ISSUE TITLE
Tags for Projects

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#83]
## Background

It is currently difficult to find projects based on certain themes.

## Tasks

- [x] Add tags to projects
- [x] Enable project filtering by tags.
- [x] Inject search param into filter when navigating to projects page.
- [x] Make project tags link to the projects page filtered to the relevant tags.
- [x] Make it possible for the URL to be update when the a search term is entered into the filter.
  - Does this once when the search param is different from an updated search term.
- [x] Waiting to Deploy
