### ISSUE TITLE
Registration Page Uplift

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#92]
## Background

As an organiser, I must be able to capture data on participants so that I can generate statistics to help with future event planning.

## Tasks

- [x] Add Age to Holder model and with different options and add to account Registrations page.
  - Under 18 Boolean to Holder model (In view: as at Friday of the Competition)
  - Other age categories to demographics in User model.
- [x] Add Region to Holder model with different Regions and add account Registration page.
  - Store as text and add "Outside Australia and NZ"
- [x] Add Demographic Data to User model.
- [x] Append Demographic field underneath the user registration form.

Other

- [x] Team Status - Looking For Team Members, Working Solo, Team Full, In Team.

## Important

- Demographic data should only be visible to the user, and to staff as a summary (not able to be linked back to any one person)

**Comment by cassar** [comment]
@Cruion , have pushed a 'demographics' branch for this for you to have a look.
