### ISSUE TITLE
Profile Page Uplift (Implementation)

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#94]
## Background

Uplift (Implement) individual profile pages to allow participants to show their skills, interests and badges.

## User Story

As a participant, I must be able to see who else has registered and what location they have registered for so that I am able to form a team with people with complementary skills and interests.

## Tasks

- [ ] Create a profile page.
- [ ] Create a profile index.
  - Add filters to the side.
- [ ] Add Main Menu link to profile page.
