### ISSUE TITLE
Implement Action Text

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#99]
## Background

Will be great greatly improve experience of writing articles on the Hackerspace.

## Tasks

- [ ] Install
- [ ] Add to Events
- [ ] Add to Challenges
- [ ] Add to Projects

**Comment by waiholiu** [comment]
@cassar  

anyone looking at this one? If not, happy to take a look at it.

**Comment by cassar** [comment]
@waiholiu , Yeah go for it!

Looking forward to having this in.

Do you have an AWS account to test photo drag and drop?

Ok if not, we can test on staging.

**Comment by waiholiu** [comment]
cool, well i haven't played around with AWS at all - but i do have experience with azure and firebase.

Is that just a matter of overriding the values in storage.yml with those of my own s3 bucket? I believe there's a 12 month trial so I'll sign up for that if it's free.

**Comment by cassar** [comment]
Nah, there is a couple of env variables that you set, check the bottom of the readme in the repo.

**Comment by waiholiu** [comment]
hey @cassar 

Some questions. So I've tried to install ActionText by running rails action_text:install as per the instructions on the site and appears like it requires a db schema change cause it produces a migration file.

Anyway, the migration file wants to create two new tables active_storage_attachment and active_storage_blobs. But these tables already exist in the schema. 

I don't know enough about rails to know what's going on - I just know that running db:migrate causes a duplicate table error (rightly, because it's trying to create tables that already exist).

So is this a clash with another library? Why do these tables already exist?

**Comment by cassar** [comment]
Hey @waiholiu ,

It's trying to reinstall [Active Storage](https://guides.rubyonrails.org/active_storage_overview.html) which is what we use uploading assets like images and PDFs.

Deleting the Migration should allow you to proceed with installation.

**Comment by waiholiu** [comment]
@cassar  - so I've checked in the work I've done at this branch https://github.com/govhackaustralia/hackerspace3/tree/actiontext

It wasn't trival to install and it didn't "just work" according to the instructions. 

I did the following changes on top of the change 

- added @import "trix/dist/trix";  to application.scss file 
- added = javascript_pack_tag 'application' to application.html.haml
- removed one of the migration files generated

I've made the changes to the edit event page to demonstrate but it doesn't look right.

Below is a screenshot of the trix-editor at the top where it's on it's own, and then later on inside a form inside the "field" class. So yeah we would need to do a bit of work styling it.

![image](https://user-images.githubusercontent.com/8047097/88067105-e895c200-cbb1-11ea-9396-d97b6fa4f7f3.png)

In addition, I can't seem to add a link, add an image etc. to the trix editor - I'm not sure why that is.

I haven't tried the Save functionality yet, although from the specified instructions, it doesn't seem like it would be that hard.
